force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Subscriptions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/MonthlyRecurrence__c.field-meta.xml
<CustomField>
    <fullName>MonthlyRecurrence__c</fullName>
    <label>Monthly Recurrence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/WeeklyRecurrence__c.field-meta.xml
<CustomField>
    <fullName>WeeklyRecurrence__c</fullName>
    <label>Weekly Recurrence</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DaysOfWeek</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <label>Default</label>
</RecordType>

force-app/main/default/classes/ExpenseFactory.cls
public class ExpenseFactory {

    private Expense__c expense;
    
    public ExpenseFactory() {
        this.expense = new Expense__c(
            RecordTypeId = Schema.SObjectType.Expense__c.getRecordTypeInfosByDeveloperName().get('Default').getRecordTypeId()
        );
    }
    
    public ExpenseFactory name(String name) {
        this.expense.Name = Name;
        return this;
    }
    
    public ExpenseFactory category(String category) {
        this.expense.Category__c = category;
        return this;
    }

    public ExpenseFactory amount(Double amount) {
        this.expense.Amount__c = amount;
        return this;
    }
    
    public ExpenseFactory day(Date day) {
        this.expense.Date__c = day;
        return this;
    }

    public ExpenseFactory monthlyRecurrence(Integer monthlyRecurrence) {
        this.expense.MonthlyRecurrence__c = Double.valueOf(monthlyRecurrence);
        return this;
    }
    
    public ExpenseFactory weeklyRecurrence(String weeklyRecurrence) {
        this.expense.WeeklyRecurrence__c = weeklyRecurrence;
        return this;
    }
    
    public Expense__c get() {
        return this.expense;
    }
      
}