force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Subscriptions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/MonthlyRecurrence__c.field-meta.xml
<CustomField>
    <fullName>MonthlyRecurrence__c</fullName>
    <label>Monthly Recurrence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/WeeklyRecurrence__c.field-meta.xml
<CustomField>
    <fullName>WeeklyRecurrence__c</fullName>
    <label>Weekly Recurrence</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DaysOfWeek</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/recordTypes/Recurrence.recordType-meta.xml
<RecordType>
    <fullName>Recurrence</fullName>
    <active>true</active>
    <label>Recurrence</label>
</RecordType>

force-app/main/default/classes/GenerateRecurrenceExpensesBatch.cls
global with sharing class GenerateRecurrenceExpensesBatch implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext batchableContext) {
        String query = 
            'SELECT Id, Amount__c, Category__c, Date__c, Name, MonthlyRecurrence__c, WeeklyRecurrence__c, RecordTypeId FROM Expense__c ' +
            'WHERE ' +
                'RecordType.DeveloperName = \'Recurrence\' AND ' +
                'Date__c = LAST_MONTH AND ' +
                '(MonthlyRecurrence__c != NULL OR ' +
                'WeeklyRecurrence__c != NULL)';

        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext batchableContext, List<Expense__c> recurrenceExpenses) {
        try {
            GenerateRecurrenceExpenses generateRecurrenceExpenses = new GenerateRecurrenceExpenses();
            generateRecurrenceExpenses.generateMonthly(recurrenceExpenses);
            generateRecurrenceExpenses.generateWeekly(recurrenceExpenses);
        } catch(Exception e) {
            System.debug('Error on batch ' + e);
        }
    }   
    
    global void finish(Database.BatchableContext batchableContext) {
        System.debug('finish');
    }
}